package org.allin.backend.dto.groq;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Response object from the Groq Chat Completions API.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ChatCompletionResponse {
    /**
     * The ID of the chat completion.
     */
    private String id;

    /**
     * The object type, typically "chat.completion".
     */
    private String object;

    /**
     * The Unix timestamp (in seconds) of when the chat completion was created.
     */
    private Long created;

    /**
     * The model used for the chat completion.
     */
    private String model;

    /**
     * The list of chat completion choices.
     */
    private List<Choice> choices;

    /**
     * Usage statistics for the completion.
     */
    private Usage usage;

    /**
     * Represents a single completion choice.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Choice {
        /**
         * The index of the choice.
         */
        private Integer index;

        /**
         * The message generated by the model.
         */
        private ChatMessage message;

        /**
         * The reason the model stopped generating text.
         */
        @JsonProperty("finish_reason")
        private String finishReason;
    }

    /**
     * Usage statistics for the completion.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Usage {
        /**
         * The number of tokens used for the prompt.
         */
        @JsonProperty("prompt_tokens")
        private Integer promptTokens;

        /**
         * The number of tokens used for the completion.
         */
        @JsonProperty("completion_tokens")
        private Integer completionTokens;

        /**
         * The total number of tokens used.
         */
        @JsonProperty("total_tokens")
        private Integer totalTokens;
    }
}
